services:
  - type: web
    name: kedi-money-network
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start --workspace=backend
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: JWT_SECRET
        value: RwandaKediNetworkSuperSecretKey123!@
      - key: ADMIN_EMAIL
        value: kedimoneynetwork@gmail.com
      - key: ADMIN_PASSWORD
        value: kedi@123
      - key: DATABASE_URL
        fromDatabase:
          name: kedi-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: kedi-db
    databaseName: kedi_db
    user: kedi_user
